export const CATEGORIES = [
	'Teléfonos',
	'Ordenadores',
	'Cámaras y Fotografía',
	'Audio',
	'Gaming',
	'Almacenamiento',
	'Electrodomésticos',
	'Otros',
]
export const SUBCATEGORIES = {
	Teléfonos: ['Smartphones', 'Accesorios', 'Tabletas', 'Carcasas', 'Cables'],
	Ordenadores: [
		'Laptops',
		'Ordenadores de Escritorio',
		'Componentes',
		'Accesorios',
		'Perifericos',
		'Cables',
	],
	Fotografía: [
		'Cámaras DSLR',
		'Cámaras Compactas',
		'Accesorios de Fotografía',
		'Iluminación',
		'Lentes',
		'Filtros',
		'Trípodes',
	],
	Audio: [
		'Audífonos',
		'Altavoces',
		'Equipos de Audio',
		'Auriculares Inalámbricos',
		'Altavoces Bluetooth',
		'Receptores de Audio',
		'Grabadoras de Voz',
		'Cables',
		'Otros',
	],
	Gaming: [
		'Videojuegos',
		'Consolas',
		'Consolas Retro',
		'Controles Especiales',
		'Realidad Virtual',
		'Sillas Gaming',
		'Accesorios de Videojuegos',
		'Ratones y Teclados Gaming',
		'Otros',
	],
	Almacenamiento: [
		'Discos Duros',
		'Memorias USB',
		'Tarjetas de Memoria',
		'Unidades de Estado Sólido (SSD)',
		'Unidades Flash',
		'Carcasas de para discos externos',
		'Otros',
	],
	Electrodomésticos: [
		'Aspiradoras',
		'Licuadoras',
		'Microondas',
		'Batidoras',
		'Cafeteras',
		'Planchas',
		'Hornos',
		'Refrigeradores',
		'Lavadoras',
		'Secadoras',
		'Robot de Cocina',
		'Ventiladores',
		'Aires Acondicionados',
		'Otros',
	],
	Otros: ['Relojes Inteligentes', 'Dispositivos IoT', 'Otros'],
}
export const STATEOFPRODUCT = [
	'Nuevo',
	'Como Nuevo',
	'Usado en Buen Estado',
	'Usado en Condiciones Aceptables',
	'Para Reparar o Piezas',
]
